### ISSUE TITLE
#require "bap.top" ends with unbound values prefixed with Core_kernel_kernel.xx

### ISSUE THREAD

**Issue by karatemonkey63** [BinaryAnalysisPlatform/bap#190]
Below is what I ran. Then tried the example playing around stuff from the start page. 

I get :

Unbound value Core_kernel_kernel.Std.Nothing.pp.
Unbound value Core_kernel_kernel.Std.Host_and_port.pp.
Unbound value Core_kernel_kernel.Std.Float.pp.
Unbound value Core_kernel_kernel.Std.Nativeint.pp.
Unbound value Core_kernel_kernel.Std.Int64.pp.
Unbound value Core_kernel_kernel.Std.Int32.pp.
Unbound value Core_kernel_kernel.Std.Int.pp.
Unbound value Core_kernel_kernel.Std.Exn.pp.

Which looks like a name is getting kernel once more than it should. 

If I try to continue with the example, I get errors with 

# let d = disassemble_file "ls";;
val d : Bap.Std.disasm Core_kernel.Std.Or_error.t =
  Core_kernel.Result.Error ("Unix.Unix_error(Unix.ENOENT, \"open\", \"ls\")")

I'm guessing there is a module dependency that ahs the name Core_kernel, that should really be Core. Then again, I have no idea. Anyway, help
_______________________________________________________________________________
root@ubuntu:/# opam install bap -e ubuntu
[NOTE] Package bap is already installed (current version is 0.9.5).
root@ubuntu:/# ocaml
        OCaml version 4.02.1

# #use "topfind";;
- : unit = ()
Findlib has been successfully loaded. Additional directives:
  #require "package";;      to load a package
  #list;;                   to list the available packages
  #camlp4o;;                to load camlp4 (standard syntax)
  #camlp4r;;                to load camlp4 (revised syntax)
  #predicates "p,q,...";;   to set these predicates
  Topfind.reset();;         to force that packages will be reloaded
  #thread;;                 to enable threads

- : unit = ()
#  #require "bap.top";;
/usr/lib/ocaml/dynlink.cma: loaded
/usr/lib/ocaml/camlp4: added to search path
/root/.opam/system/lib/type_conv: added to search path
/usr/lib/ocaml/unix.cma: loaded
/usr/lib/ocaml/bigarray.cma: loaded
/root/.opam/system/lib/bin_prot: added to search path
/root/.opam/system/lib/bin_prot/bin_prot.cma: loaded
/root/.opam/system/lib/comparelib: added to search path
/root/.opam/system/lib/comparelib/comparelib.cma: loaded
/root/.opam/system/lib/custom_printf: added to search path
/root/.opam/system/lib/custom_printf/custom_printf.cma: loaded
/root/.opam/system/lib/variantslib: added to search path
/root/.opam/system/lib/variantslib/variantslib.cma: loaded
/root/.opam/system/lib/sexplib: added to search path
/root/.opam/system/lib/sexplib/sexplib.cma: loaded
/root/.opam/system/lib/enumerate: added to search path
/root/.opam/system/lib/fieldslib: added to search path
/root/.opam/system/lib/fieldslib/fieldslib.cma: loaded
/root/.opam/system/lib/pa_bench: added to search path
/root/.opam/system/lib/pa_bench/pa_bench_lib.cma: loaded
/root/.opam/system/lib/oUnit: added to search path
/root/.opam/system/lib/oUnit/oUnitAdvanced.cma: loaded
/root/.opam/system/lib/oUnit/oUnit.cma: loaded
/root/.opam/system/lib/pa_ounit: added to search path
/root/.opam/system/lib/pa_ounit/pa_ounit_lib.cma: loaded
/root/.opam/system/lib/pa_test: added to search path
/root/.opam/system/lib/pa_test/pa_test_lib.cma: loaded
/root/.opam/system/lib/typerep_lib: added to search path
/root/.opam/system/lib/typerep_lib/typerep_lib.cma: loaded
/root/.opam/system/lib/core_kernel: added to search path
/root/.opam/system/lib/core_kernel/core_kernel.cma: loaded
/root/.opam/system/lib/herelib: added to search path
/root/.opam/system/lib/faillib: added to search path
/usr/lib/ocaml/compiler-libs: added to search path
/root/.opam/system/lib/bitstring: added to search path
/root/.opam/system/lib/bitstring/bitstring.cma: loaded
/root/.opam/system/lib/bap: added to search path
/root/.opam/system/lib/bap/elf.cma: loaded
/root/.opam/system/lib/zarith: added to search path
/root/.opam/system/lib/zarith/zarith.cma: loaded
/root/.opam/system/lib/bap/types.cma: loaded
/root/.opam/system/lib/bap/dwarf.cma: loaded
/root/.opam/system/lib/bap/bap_image.cma: loaded
/root/.opam/system/lib/camlzip/../zip: added to search path
/root/.opam/system/lib/camlzip/../zip/zip.cma: loaded
/root/.opam/system/lib/bap/disasm.cma: loaded
/root/.opam/system/lib/findlib: added to search path
/root/.opam/system/lib/bap/bap.cma: loaded
/root/.opam/system/lib/bap/elf_backend.cma: loaded
/root/.opam/system/lib/bap/llvm.cma: loaded
/root/.opam/system/lib/bap/plugins.cma: loaded
/root/.opam/system/lib/bap/top.cma: loaded
Unbound value Core_kernel_kernel.Std.Nothing.pp.
Unbound value Core_kernel_kernel.Std.Host_and_port.pp.
Unbound value Core_kernel_kernel.Std.Float.pp.
Unbound value Core_kernel_kernel.Std.Nativeint.pp.
Unbound value Core_kernel_kernel.Std.Int64.pp.
Unbound value Core_kernel_kernel.Std.Int32.pp.
Unbound value Core_kernel_kernel.Std.Int.pp.
Unbound value Core_kernel_kernel.Std.Exn.pp.
#

**Comment by ivg** [comment]
it is fixed in the latest master, and in 0.9.6 release

**Comment by ivg** [comment]
Actually, this was just a warnings, let me help you:

```
# let d = disassemble_file "ls";;
val d : Bap.Std.disasm Core_kernel.Std.Or_error.t =
Core_kernel.Result.Error ("Unix.Unix_error(Unix.ENOENT, \"open\", \"ls\")")
```

`disassemble_file` takes a path to file and disassembles it. The output is just saying to you, that there is no such file as "ls". You may try `"/bin/ls"`, for instance.

What concerning this unbound values, I've fixed them many weeks ago, but they really doesn't affect  anything, just warnings.

**Comment by karatemonkey63** [comment]
Even with the full path to bin, was still getting 
val d : Bap.Std.disasm Core_kernel.Std.Or_error.t =
Core_kernel.Result.Error ("Unix.Unix_error(Unix.ENOENT, \"open\", \"ls\")")

**Comment by ivg** [comment]
according to the error message:

```
Core_kernel.Result.Error ("Unix.Unix_error(Unix.ENOENT, \"open\", \"ls\")")
                                                                                                            ^^^^^^
```
You're still trying to open "ls" that is in your local folder, not "/bin/ls"

**Comment by karatemonkey63** [comment]
Sorry about that. I copied the wrong screen. I was using the full path and getting the error. However, it turns out it was a problem with installation of OCAML. Somehow the core module wasn't installed. 

----- Original Message -----

**Comment by ivg** [comment]
That's not possible =) Core module is not needed to be initialized.
